---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: "Include acme.ansible_role_install_docker"
      ansible.builtin.include_role:
        name: "acme.ansible_role_install_docker"
